spring:
  application:
    name: egreso-service

  profiles:
    active: dev

  cloud:
    compatibility-verifier:
      enabled: false

    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8084

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true