spring.application.name=egreso-service

server.port=8084

spring.profiles.active=dev

spring.cloud.compatibility-verifier.enabled=false
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
